gcn-si: fix named module parameter declaration
This patch fixes the following build error due to an incorrect module
parameter declaration.

drivers/input/si/gcn-si.c:130: error: expected ')' before 'int'
make[2]: *** [drivers/input/si/gcn-si.o] Error 1
make[1]: *** [drivers/input/si] Error 2
make: *** [drivers] Error 2

Signed-off-by: Albert Herranz <albert_herranz@yahoo.es>